### PR TITLE
cooooode

### PR DESCRIPTION
**Pull request by lukaus**

### CODE REVIEW

**Comment by Riuchando** [comment]
dfhdfhdfhdfhdfhdfhdfhsfrdesdagsaate

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by lukaus** [comment]
ok

**Comment by Riuchando** [comment]
poop

**Comment by Riuchando** [comment]
An array of game object, it makes it much simpler.  When you instantiate it returns the gameObject. Add them to the array and them call the game object.  GREP.  I lika do the chacha, and...

**Comment by lukaus** [comment]
I hereby give up on this request.

**Pull request closed without merging**
